# ===================================
#  Relation Behavior Config
# ===================================

person:
    label: Person
    view:
        list: ~/plugins/october/test/models/person/columns.yaml
        form: ~/plugins/october/test/controllers/people/preview_fields.yaml

    list:
        form: ~/plugins/october/test/models/person/columns.yaml
        list: ~/plugins/october/test/controllers/people/preview_fields.yaml

    manage:
        list: ~/plugins/october/test/models/person/columns.yaml
        form: ~/plugins/october/test/models/person/fields.yaml
